- name: Verify File Server Role is installed.
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

# "Ethernet 2" for WinSrv
- name: find domain_adapter
  set_fact:
    domain_adapter="{{item.connection_name}}"
  when: item.ipv4.address == hostvars[dict_key].ansible_host
  with_items: "{{ ansible_interfaces }}"
  run_once: true

- name: Set DC as a DNS server
  win_dns_client:
    adapter_names: "{{domain_adapter}}"
    ipv4_addresses:
    - "{{hostvars[dns_domain].ansible_host}}"

- name: Add member server
  microsoft.ad.membership:
    dns_domain_name: "{{ member_domain }}"
    domain_admin_user: "{{ domain_user }}"
    domain_admin_password: "{{ domain_password }}"
    state: domain
    reboot: true
#
# - name: Reboot if needed
#   win_reboot:
#     reboot_timeout: 1500
#     post_reboot_delay: 100
#   when: domain_state.reboot_required
