- name: Ensure domain exists
  microsoft.ad.domain:
    domain_netbios_name: "{{netbios_name}}"
    dns_domain_name: "{{domain}}"
    safe_mode_password: "{{domain_password}}"
  register: check_domain

- name: Reboot to complete domain creation
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 300
  when: check_domain.changed

- name: Ensure server is a DC
  microsoft.ad.domain_controller:
    dns_domain_name: "{{domain}}"
    domain_admin_user: "{{domain_username}}"
    domain_admin_password: "{{domain_password}}"
    safe_mode_password: "{{domain_password}}"
    state: domain_controller
  register: check_domain_controller

# "clild_domain":"add child domain to parent domain" fails with "Unable to find a default server with Active Directory Web Services running."
- name: ensure ADWS is running
  ansible.windows.win_shell: Set-Service -Name adws -StartupType Automatic

- name: Reboot to complete domain controller setup
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: check_domain_controller.changed

- name: Ensure DNS feature is installed
  win_feature:
    name: DNS
    state: present

- name: Ensure Administrator is part of Enterprise Admins
  microsoft.ad.group:
    name: "Enterprise Admins"
    members:
      set:
        - Administrator

- name: Ensure Administrator is part of Domain Admins
  microsoft.ad.group:
    name: "Domain Admins"
    members:
      set:
        - Administrator
