# "Ethernet" for Win10
- name: find domain_adapter
  set_fact:
    domain_adapter="{{item.connection_name}}"
  when: item.ipv4.address == hostvars[dict_key].ansible_host
  with_items: "{{ ansible_interfaces }}"
  run_once: true

- name: Set DC as a DNS server
  win_dns_client:
    adapter_names: "{{domain_adapter}}"
    ipv4_addresses:
    - "{{hostvars[dns_domain].ansible_host}}"

- name: Add member workstation
  microsoft.ad.membership:
    dns_domain_name: "{{ member_domain }}"
    domain_admin_user: "{{ domain_user }}"
    domain_admin_password: "{{ domain_password }}"
    state: domain
    reboot: true
  register: domain_state
