---
- name: Prepare domains
  hosts: parent_dc
  vars_files:
    - ./config.json
  roles:
  - settings/domain_controller
  vars:
    domain: "{{hosts[dict_key].domain}}"
    domain_username: "{{admin_user}}@{{domain}}"
    domain_password: "{{domains[domain].domain_password}}"
    netbios_name: "{{domains[domain].netbios_name}}"

